-- Script de Insert para a tabela area --

INSERT INTO area ( area) VALUES
    ( 'Engenharia civil'),
    ( 'Saúde Mental'),
    ( 'Saúde'),
    ( 'Meio Ambiente'),
    ( 'Economia'),
    ( 'Agricultura Sustentável'),
    ('Tecnologia'),
    ( 'Biologia'),
    ( 'Educação'),
    ( 'Mudança Climática'),
    ( 'Nutrição'),
    ( 'Oncologia'),
    ( 'Sociologia'),
    ( 'Saúde Pública'),
    ('Genética'),
    ('Agricultura'),
    ( 'Epidemiologia'),
    ('Astronomia'),
    ('Microbiologia'),
    ('Engenharia Ambiental'),
    ('Oceanografia'),
    ('Ecologia'),
    ('Inclusão'),
    ('Imunologia'),
    ('Bioquímica'),
    ('Medicina'),
    ('Biologia Molecular'),
    ('Consumo Consciente'),
    ('Ecoturismo'),
    ('Conservação Marinha'),
    ('Segurança da Informação'),
    ('Energia Renovável'),
    ('Biologia da conservação'),
    ('Engenharia agrícola'),
    ('Farmacologia'),
    ('Indústria Sustentável'),
    ('Políticas Públicas'),
    ('Recursos Hídricos'),
    ('Transporte'),
    ('Ciência da Computação'),
    ('Engenharia química'),
    ('Energia'),
    ('Engenharia de Materiais'),
    ('Química'),
    ('Geologia'),
    ('Engenharia de Transportes'),
    ('Engenharia elétrica'),
    ('Engenharia'),
    ('Agroecologia'),
    ('Ecologia de paisagem'),
    ('Comunicação'),
    ('Antropologia'),
    ('Sustentabilidade'),
    ('Física'),
    ('Zoologia'),
    ('Geografia'),
    ('Cultura'),
    ('Moradia Digna'),
    ('Saneamento Básico'),
    ('Psicologia'),
    ('Inclusão no Mercado de Trabalho'),
    ('Biologia/Medicina'),
    ('Empreendedorismo'),
    ('Justiça Social'),
    ('Direitos Humanos'),
    ('Urbanização'),
    ('Demografia'),
    ('Climatologia'),
    ('Turismo Sustentável'),
    ('Conservação Terrestre'),
    ('Neurociência'),
    ('Toxicologia ambiental'),
    ('Planejamento Urbano');
    



